name: 'Dependency Check'
description: 'Github action to execute dependency check as part of a github workflow'
Author: 'javixeneize'
branding:
  icon: 'shield'  
  color: 'red'
inputs:
    project:
        required: true
    path:
        required: true  
    format:
        required: true
    others:
        required: false
runs:
    using: 'docker'
    image: 'docker://owasp/dependency-check-action:latest@sha256:98d9c2f1ddd8c649e9b0b16cd22f0926136df2784a93697de2ccd9f9b491e923'
    env:
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_OTHERS: ${{ inputs.others }}
    args:

        - '--project'
        - '$INPUT_PROJECT'
        - '--scan'
        - '$INPUT_PATH'
        - '--format' 
        - '$INPUT_FORMAT'
        - '--out'
        -  '/github/workspace/reports'
        - '--noupdate'
        - '$INPUT_OTHERS'
